### ISSUE TITLE
Incorrect maximum flow rate in device schema?

### ISSUE THREAD

**Issue by RoboDoig** [harp-tech/device.olfactometer#23]
Per the olfactometer readme, I had expected there to be 4 lines with 0-100ml/min flow rate and one line (carrier) with 0-1000ml/min. According to the [device schema](https://github.com/harp-tech/device.olfactometer/blob/b39b4c0e566bd45d1a813e0e1781762549667717/device.yml#L86), both channels 3 and 4 have flow ranges of 0-1000ml/min. Is this a mistake in the schema or is this the intended range?

**Comment by artursilva0** [comment]
It is the intended range, since channel 3 can be configured with different ranges: 0-100ml/min or 0-1000ml/min using the `Channel3Range` register.

**Comment by RoboDoig** [comment]
@artursilva0 - thank you, had missed that!
